### PR TITLE
Switch to `poetry`

### PR DESCRIPTION
**Pull request by sandrobonazzola**
## Changes introduced with this PR

removed `requirements.txt` as we are using `poetry` for managing requirements.
Updated `README.md` and `pyproject.toml` accordingly.
As a consequence, updated `poetry.lock` and `Dockerfile` to match above changes.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by portante — COMMENTED** [review]
The PR header says update `pyproject`, but it looks like a blank like was added only.  The conversion to use `poetry` seems a bit more descrptive, as well as updates to the `Dockerfile`.

**Comment by sandrobonazzola** [comment]
> . The conversion to use `poetry` seems a bit more descrptive

updated PR title

**Comment by portante** [comment]
One of the unfortunate things about GitHub is the PR description vs commit message.  We really should be updating the commit message as well.

**Review by portante — CHANGES_REQUESTED** [review]
Can you consider updating the commit message via `git commit --amend`?

**Review by portante — APPROVED** [review]

**Review by jaredoconnell — APPROVED** [review]
Looks good to me. It works when I test it with Docker Compose. Though for some reason it doesn't like my venv.

Installing dependencies from lock file

```
  SolverProblemError

  Because no versions of twisted match >=22.4.0,<22.8.0 || >22.8.0
   and arcaflow-plugin-sdk (0.9.0) depends on twisted (>=22.4.0), arcaflow-plugin-sdk (0.9.0) requires twisted (22.8.0).
  And because twisted (22.8.0) depends on zope.interface (>=4.4.2), arcaflow-plugin-sdk (0.9.0) requires zope.interface (>=4.4.2).
  So, because no versions of zope.interface match >=4.4.2
   and arcaflow-plugin-uperf depends on arcaflow-plugin-sdk (0.9.0), version solving failed.

```

**Pull request merged**
