### PR TITLE
Switch to bytes

### LINKED ISSUE #20: uperf plugin should support packet sizes in bytes
## Describe the bug

The uperf plugin currently accepts a `size` value for flowops that according to the schema is in kibbibytes. Usual uperf tests often need to be done with sub-KiB sizes. This should be changed in the plugin to accept values in bytes.

## To reproduce

Run a uperf plugin workload with a size value of `64`. The test will be run with 64KiB packets instead of 64B packets.

### PR DESCRIPTION
**Pull request by jaredoconnell**
Fixes #20 

## Changes introduced with this PR
This PR allows you to set the size fields as bytes instead of only units of KiB.
It also uses the new unit feature of the SDK, which will make it so future GUIs can help the user pick sizes that are units of kib, mb, etc.

I also updated formatting with the `black` formatter, and validated with flake8, and I added a flake8 config file.

This PR is based on the housekeeping PR's branch, so it's recommended that you review that first, and only review the latest commit on this PR.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jaredoconnell** [comment]
You can test this in a workflow with the tag `switch-to-bytes_cdd00cf`

**Comment by portante** [comment]
Converting to `Draft` until PR #21 is merged.

**Review by dustinblack — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
Please `git rebase` this PR on `main` so we can see these changes in isolation after the reported conflicts are resolved.

**Review by portante — APPROVED** [review]
Looks good, but tests are failing.

**Comment by jaredoconnell** [comment]
I'm merging this. The prior test failure was just due to it taking too long to build. The cause of that is many stages, each with dnf installs, and needs to be addressed as an extension of the timeout. To be safe, 10 minutes would be best.

**Pull request merged**
